
package br.com.store.model.service.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import br.com.store.model.service.impl.ProductServiceBean;

/**
 * This class was generated by the CXF 2.0.1-incubator
 * Sun Sep 28 16:50:18 BRT 2008
 * Generated source version: 2.0.1-incubator
 * 
 */

@WebServiceClient(name = "ProductServiceBeanService", targetNamespace = "http://impl.service.model.store.com.br/", wsdlLocation = "file:wsdl/ProductService.wsdl")
public class ProductServiceBeanService extends Service {

    private final static URL WSDL_LOCATION;
    private final static QName SERVICE = new QName("http://impl.service.model.store.com.br/", "ProductServiceBeanService");
    private final static QName ProductServiceBeanPort = new QName("http://impl.service.model.store.com.br/", "ProductServiceBeanPort");
    static {
        URL url = null;
        try {
            url = new URL("file:wsdl/ProductService.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:wsdl/ProductService.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public ProductServiceBeanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductServiceBeanService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns ProductServiceBeanPort
     */
    @WebEndpoint(name = "ProductServiceBeanPort")
    public ProductServiceBean getProductServiceBeanPort() {
        return (ProductServiceBean)super.getPort(ProductServiceBeanPort, ProductServiceBean.class);
    }

}
