
package br.com.store.model.service.impl;

import javax.jws.WebParam.Mode;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding.Style;
import javax.jws.soap.SOAPBinding;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the CXF 2.0.1-incubator
 * Sun Sep 28 16:50:18 BRT 2008
 * Generated source version: 2.0.1-incubator
 * 
 */

@WebService(targetNamespace = "http://impl.service.model.store.com.br/", name = "ProductServiceBean")

public interface ProductServiceBean {

    @WebResult(targetNamespace = "", name = "return")
    @RequestWrapper(localName = "getAll", targetNamespace = "http://impl.service.model.store.com.br/", className = "br.com.store.model.service.impl.GetAll")
    @ResponseWrapper(localName = "getAllResponse", targetNamespace = "http://impl.service.model.store.com.br/", className = "br.com.store.model.service.impl.GetAllResponse")
    @WebMethod
    public java.util.List<br.com.store.model.service.impl.Product> getAll();
}
